### ISSUE TITLE
add an action to validate updates to hub config files

### ISSUE THREAD

**Issue by elray1** [hubverse-org/hubverse-actions#9]
this would make me feel better about things when i'm making updates to config files

**Comment by zkamvar** [comment]
I can give this a shot. I had initially thought this was completed in https://github.com/hubverse-org/hubverse-actions/commit/b59f6bc121540a99de2f2bfbeaefcdc9a14ec89f, but now I understand that doesn't validate the config files, so this action would be, in a sense, validating the validators. 

I'm going to implement an action that will use `hubValidations::check_config_hub_valid()` to validate the config files because it looks like it wraps the validations from `hubAdmin`

As a side note: I believe a workflow like this would have prevented the config errors I was getting in https://github.com/hubverse-org/hubDocs/issues/152

> - 🤔 Validating config files
>   - 👍🏽 installed hubAdmin package
>   - 🤔 `validate_hub_config()` fails for metadata schema because some elements need to be arrays

**Comment by annakrystalli** [comment]
Sorry I should have added more detail in the request!

Yes the config is checked during submission validation but that's only triggered when model metadata files are submitted.

It would be nice to have a workflow that is triggered by changes to the config.

The hubValidations check function actually only wraps a `hubAdmin` function specifically [`hubAdmin::validate_hub_config()`](https://hubverse-org.github.io/hubAdmin/reference/validate_hub_config.html). So we only need to run this function.

This returns `TRUE` or `FALSE` so we want the workflow to fail if it returns `FALSE`. If `FALSE`, and `errors` table is also attached as an attribute.

There's also function [`hubAdmin:: view_config_val_errors()`](https://hubverse-org.github.io/hubAdmin/reference/view_config_val_errors.html) that presents any validation errors in a nicely formates `gt` table. Would be amazing to post that as a comment but not sure how straight forward it will be. If not just printing the errors attribute would be useful instead.

**Comment by zkamvar** [comment]
currently testing things out in https://github.com/zkamvar/example-simple-forecast-hub/actions/runs/10201766462/job/28224400302?pr=1

**Comment by zkamvar** [comment]
Okay, I've got something working here:

https://github.com/zkamvar/example-complex-forecast-hub/pull/1

(because I'm going to delete my fork, it looks like this:)

## :x: Invalid Configuration


The schema in `hub-config/` appear to be invalid. Details about the exact locations of the errors can be found in the table below.
<div id="yeuwgcyyug" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
  
  <table class="gt_table" style="-webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale; font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'; display: table; border-collapse: collapse; line-height: normal; margin-left: 2%; margin-right: 2%; color: #333333; font-size: 16px; font-weight: normal; font-style: normal; background-color: #FFFFFF; width: auto; border-top-style: solid; border-top-width: 2px; border-top-color: #A8A8A8; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #A8A8A8; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; table-layout: fixed;" data-quarto-disable-processing="false" data-quarto-bootstrap="false" bgcolor="#FFFFFF">
  <colgroup>
    <col>
    <col>
    <col>
    <col>
    <col style="width:16.6666666666667%;">
    <col style="width:25%;">
    <col style="width:16.6666666666667%;">
  </colgroup>
  <thead style="border-style: none;">
    <tr class="gt_heading" style="border-style: none; background-color: #F0F3F5; text-align: center; border-bottom-color: #FFFFFF; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3;" bgcolor="#F0F3F5" align="center">
      <td colspan="7" class="gt_heading gt_title gt_font_normal" style="border-style: none; color: #333333; font-size: 125%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; border-bottom-width: 0; background-color: #F0F3F5; text-align: center; border-bottom-color: #FFFFFF; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; font-weight: normal;" bgcolor="#F0F3F5" align="center"><span class="gt_from_md"><strong style="margin-top: 0; margin-bottom: 0;"><code>hubUtils</code> config validation error report</strong></span></td>
    </tr>
    <tr class="gt_heading" style="border-style: none; background-color: #F0F3F5; text-align: center; border-bottom-color: #FFFFFF; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3;" bgcolor="#F0F3F5" align="center">
      <td colspan="7" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style="border-style: none; color: #333333; font-size: 85%; padding-top: 3px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; border-top-color: #FFFFFF; border-top-width: 0; background-color: #F0F3F5; text-align: center; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; font-weight: normal;" bgcolor="#F0F3F5" align="center"><span class="gt_from_md">Report for directory <strong style="margin-top: 0;"><code>/home/runner/work/example-complex-forecast-hub/example-complex-forecast-hub/hub-config</code></strong> using
schema version <a href="https://github.com/hubverse-org/schemas/tree/main/v3.0.0" style="margin-bottom: 0;"><strong>v3.0.0</strong></a></span></td>
    </tr>
    <tr class="gt_col_headings gt_spanner_row" style="border-style: none; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; border-bottom-style: hidden;">
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="3" scope="colgroup" id="&lt;span class='gt_from_md'&gt;&lt;strong&gt;Error location&lt;/strong&gt;&lt;/span&gt;" style="border-style: none; color: #333333; background-color: #F0F3F5; font-size: 100%; font-weight: bold; text-transform: inherit; padding-top: 0; padding-bottom: 0; padding-right: 4px; text-align: center; padding-left: 0;" bgcolor="#F0F3F5" align="center">
        <span class="gt_column_spanner" style="border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; overflow-x: hidden; display: inline-block; width: 100%;"><span class="gt_from_md"><strong style="margin-top: 0; margin-bottom: 0;">Error location</strong></span></span>
      </th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="3" scope="colgroup" id="&lt;span class='gt_from_md'&gt;&lt;strong&gt;Schema details&lt;/strong&gt;&lt;/span&gt;" style="border-style: none; color: #333333; background-color: #F0F3F5; font-size: 100%; font-weight: bold; text-transform: inherit; padding-top: 0; padding-bottom: 0; padding-left: 4px; padding-right: 4px; text-align: center;" bgcolor="#F0F3F5" align="center">
        <span class="gt_column_spanner" style="border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; overflow-x: hidden; display: inline-block; width: 100%;"><span class="gt_from_md"><strong style="margin-top: 0; margin-bottom: 0;">Schema details</strong></span></span>
      </th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="1" scope="col" id="&lt;span class='gt_from_md'&gt;&lt;strong&gt;Config&lt;/strong&gt;&lt;/span&gt;" style="border-style: none; color: #333333; background-color: #F0F3F5; font-size: 100%; font-weight: bold; text-transform: inherit; padding-top: 0; padding-bottom: 0; padding-left: 4px; text-align: center; padding-right: 0;" bgcolor="#F0F3F5" align="center">
        <span class="gt_column_spanner" style="border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; overflow-x: hidden; display: inline-block; width: 100%;"><span class="gt_from_md"><strong style="margin-top: 0; margin-bottom: 0;">Config</strong></span></span>
      </th>
    </tr>
    <tr class="gt_col_headings" style="border-style: none; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3;">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="fileName" style="border-style: none; color: #333333; background-color: #F0F3F5; font-size: 100%; font-weight: bold; text-transform: inherit; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 6px; padding-left: 5px; padding-right: 5px; overflow-x: hidden; text-align: left;" bgcolor="#F0F3F5" valign="bottom" align="left">fileName</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="instancePath" style="border-style: none; color: #333333; background-color: #F0F3F5; font-size: 100%; font-weight: bold; text-transform: inherit; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 6px; padding-left: 5px; padding-right: 5px; overflow-x: hidden; text-align: left;" bgcolor="#F0F3F5" valign="bottom" align="left">instancePath</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="schemaPath" style="border-style: none; color: #333333; background-color: #F0F3F5; font-size: 100%; font-weight: bold; text-transform: inherit; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 6px; padding-left: 5px; padding-right: 5px; overflow-x: hidden; text-align: left;" bgcolor="#F0F3F5" valign="bottom" align="left">schemaPath</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="keyword" style="border-style: none; color: #333333; background-color: #F0F3F5; font-size: 100%; font-weight: bold; text-transform: inherit; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 6px; padding-left: 5px; padding-right: 5px; overflow-x: hidden; text-align: center;" bgcolor="#F0F3F5" valign="bottom" align="center">keyword</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="message" style="border-style: none; color: #333333; background-color: #F0F3F5; font-size: 100%; font-weight: bold; text-transform: inherit; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 6px; padding-left: 5px; padding-right: 5px; overflow-x: hidden; text-align: center;" bgcolor="#F0F3F5" valign="bottom" align="center">message</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="schema" style="border-style: none; color: #333333; background-color: #F0F3F5; font-size: 100%; font-weight: bold; text-transform: inherit; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 6px; padding-left: 5px; padding-right: 5px; overflow-x: hidden; text-align: left;" bgcolor="#F0F3F5" valign="bottom" align="left">schema</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="data" style="border-style: none; color: #333333; background-color: #F0F3F5; font-size: 100%; font-weight: bold; text-transform: inherit; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 6px; padding-left: 5px; padding-right: 5px; overflow-x: hidden; text-align: center;" bgcolor="#F0F3F5" valign="bottom" align="center">data</th>
    </tr>
  </thead>
  <tbody class="gt_table_body" style="border-style: none; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3;">
    <tr style="border-style: none;"><td headers="fileName" class="gt_row gt_left" style="border-style: none; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; margin: 10px; border-top-style: solid; border-top-width: 1px; border-top-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; overflow-x: hidden; text-align: left;" valign="middle" align="left">admin.json</td>
<td headers="instancePath" class="gt_row gt_left" style="border-style: none; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; margin: 10px; border-top-style: solid; border-top-width: 1px; border-top-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; overflow-x: hidden; text-align: left; white-space: pre;" valign="middle" align="left"><span class="gt_from_md"><strong style="margin-top: 0;">contact</strong>
└<strong style="margin-bottom: 0;">name</strong></span></td>
<td headers="schemaPath" class="gt_row gt_left" style="border-style: none; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; margin: 10px; border-top-style: solid; border-top-width: 1px; border-top-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; overflow-x: hidden; text-align: left; white-space: pre;" valign="middle" align="left"><span class="gt_from_md">properties
└<strong style="margin-top: 0;">contact</strong>
└─properties
└──<strong>name</strong>
└───<strong style="margin-bottom: 0;">type</strong></span></td>
<td headers="keyword" class="gt_row gt_center" style="border-style: none; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; margin: 10px; border-top-style: solid; border-top-width: 1px; border-top-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; overflow-x: hidden; text-align: center;" valign="middle" align="center">type</td>
<td headers="message" class="gt_row gt_center" style="border-style: none; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; margin: 10px; border-top-style: solid; border-top-width: 1px; border-top-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; overflow-x: hidden; text-align: center; background-color: #F9E3D6; font-weight: bold;" bgcolor="#F9E3D6" valign="middle" align="center">❌ must be string</td>
<td headers="schema" class="gt_row gt_left" style="border-style: none; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; margin: 10px; border-top-style: solid; border-top-width: 1px; border-top-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; overflow-x: hidden; text-align: left; white-space: pre-wrap;" valign="middle" align="left"><span class="gt_from_md">string</span></td>
<td headers="data" class="gt_row gt_center" style="border-style: none; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; margin: 10px; border-top-style: solid; border-top-width: 1px; border-top-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; overflow-x: hidden; text-align: center; background-color: #F9E3D6; font-weight: bold;" bgcolor="#F9E3D6" valign="middle" align="center">Maintainer!!!?, name?&gt;??</td></tr>
  </tbody>
  <tfoot class="gt_sourcenotes" style="border-style: none; color: #333333; background-color: #FFFFFF; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3;" bgcolor="#FFFFFF">
    <tr style="border-style: none;">
      <td class="gt_sourcenote" colspan="7" style="border-style: none; font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px;"><span class="gt_from_md">For more information, please consult the
<a href="https://hubdocs.readthedocs.io/en/latest/" style="margin-top: 0; margin-bottom: 0;"><strong><code>hubDocs</code> documentation</strong>.</a></span></td>
    </tr>
  </tfoot>
  
</table>
</div>
